stages:
  fetch_training:
    cmd: python src/fetch_training_data.py
    outs:
      - data/new_training_data.csv
  preprocess_training:
    cmd: python src/preprocess_training.py
    deps:
      - data/new_training_data.csv
    outs:
      - data/processed_training_data.csv
  update_model:
    cmd: python src/update_model.py
    deps:
      - data/processed_training_data.csv
    outs:
      - models/model.pkl
  fetch_prediction:
    cmd: python src/fetch_prediction_data.py
    outs:
      - data/new_prediction_data.csv
  preprocess_prediction:
    cmd: python src/preprocess_prediction.py
    deps:
      - data/new_prediction_data.csv
      - data/new_training_data.csv
    outs:
      - data/processed_prediction_data.csv
  predict:
    cmd: python src/make_predictions.py
    deps:
      - data/processed_prediction_data.csv
      - models/model.pkl
    outs:
      - results/predictions.csv
  send_predictions:
    cmd: python src/send_predictions.py
    deps:
      - results/predictions.csv